### ISSUE TITLE
report_aeroo: Aeroo DOCS related error!

### ISSUE THREAD

**Issue by vsnetvn** [aeroo/aeroo_reports#104]
I have a problem when exporting report xls from odoo but aeroo-docs error

> 2018-03-16 03: 27: 57,669 30478 ERROR odoo8 report_aeroo: Aeroo DOCS related error!
> Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/opt/odoo/addons/report_aeroo/report_aeroo.py", line 590, in create_aeroo_report
>     data = self._generate_doc (docs_client, data, report_xml, print_id, deferred)
>   File "/opt/odoo/addons/report_aeroo/report_aeroo.py", line 449, in _generate_doc
>     data = docs.convert (identifier = token, out_mime = mime_dict [report_xml.out_format.code], in_mime = mime_dict [report_xml.in_format])
>   File "/opt/odoo/addons/report_aeroo/docs_client_lib.py", line 121, in convert
>     self.url, data = json.dumps (payload), headers = HEADERS) .json ()
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
>     return json.loads (self.text, ** kwargs)
>   File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
>     return _default_decoder.decode (s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode (s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
>     return self.scan_once (s, idx = _w (s, idx) .end ()
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2018-03-16 03: 27: 57,669 30478 INFO odoo8 report_aeroo: End process report.borrowing_report (borrowing.report.wizard), elapsed time: 45.0733981133
> Traceback (most recent call last):
>   File "/opt/odoo/addons/report_aeroo/report_aeroo.py", line 590, in create_aeroo_report
>     data = self._generate_doc (docs_client, data, report_xml, print_id, deferred)
>   File "/opt/odoo/addons/report_aeroo/report_aeroo.py", line 449, in _generate_doc
>     data = docs.convert (identifier = token, out_mime = mime_dict [report_xml.out_format.code], in_mime = mime_dict [report_xml.in_format])
>   File "/opt/odoo/addons/report_aeroo/docs_client_lib.py", line 121, in convert
>     self.url, data = json.dumps (payload), headers = HEADERS) .json ()
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
>     return json.loads (self.text, ** kwargs)
>   File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
>     return _default_decoder.decode (s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode (s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
>     return self.scan_once (s, idx = _w (s, idx) .end ()
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2018-03-16 03: 27: 57,669 30478 INFO odoo8 report_aeroo: End total process report.borrowing_report (borrowing.report.wizard), total elapsed time: 45.0736470222

Install aroo_report with odo 8 on ubuntu 14.04

$ service aeroo-docs start
Starting Aeroo DOCS process...
Unable to lock on the pidfile.

Test config success
Success! Connection to the DOCS service was successfully established and PDF convertion is working.

Is there any idea how to fix it?
Thank you so much

**Comment by sraps** [comment]
It is most likely that you have 2 aeroo_docs processes running.

**Comment by vsnetvn** [comment]
no it's only processes run

**Comment by sraps** [comment]
Could you check access rights for the user running the aeroo_docs process on the file pidfile or the folder.

**Comment by vsnetvn** [comment]
Obstructive So I reinstalled the server ok

**Comment by sraps** [comment]
So is the problem gone?
