### ISSUE TITLE
'dict' object is not callable

### ISSUE THREAD

**Issue by mstuttgart** [aeroo/aeroo_reports#45]
When I run AerooReports in Odoo v8 in menu *configuration->Configure Docs Connection*, it return the following error:

**'dict' object is not callable**

This error is on [docs_client_lib.py]  (https://github.com/aeroo/aeroo_reports/blob/master/report_aeroo/docs_client_lib.py) file in **branch: 8.0**:

* Line 101
https://github.com/aeroo/aeroo_reports/blob/master/report_aeroo/docs_client_lib.py#L101

* Line 121:
https://github.com/aeroo/aeroo_reports/blob/master/report_aeroo/docs_client_lib.py#L121

* Line 133:
https://github.com/aeroo/aeroo_reports/blob/master/report_aeroo/docs_client_lib.py#L133

I fixed it, removing the '()' after of json variable.

Example:
* Before:  
```
response = requests.post(self.url, data = a, headers=HEADERS).json()
```
* Fixed:
```
response = requests.post(self.url, data = a, headers=HEADERS).json
```

**Comment by mstuttgart** [comment]
I will make a fork and submit the changes.

**Comment by lukebranch** [comment]
@mstuttgart ,

Thanks for your fix, i've implemented it my local instance. I've run into another issue during the Aeroo DOCS configuration wizard as follows:

Failure! Connection to DOCS service was not esatblished or convertion to PDF unsuccessful!

Details:
argument of type 'instancemethod' is not iterable

The steps to reproduce are included in the draft installation guide for Ubuntu 14.04/Odoo 8.0 here:

https://github.com/aeroo/aeroo_reports/issues/47

If you have time, I would appreciate your input or advice on this error.
