### ISSUE TITLE
Chinese character becomes empty box

### ISSUE THREAD

**Issue by mfzoutsource** [aeroo/aeroo_reports#65]
Hi, I'm facing a problem to display chinese characters in report.

https://github.com/aeroo/aeroo_docs/issues/17

**Comment by sraps** [comment]
A) If the output format is ODT/ODS, you should verify if the correct font is installed used on the client's computer that open's the document. Server need no font presence in this case.

B) If the output format is PDF, you should verify if the correct font is installed on the server that is converting the document to PDF (where OpenOffice/LibreOffice is installed). Make sure that OO/LO sees that font. Make sure that font is being included in the PDF (if it is not generic for the client's computer). In this case it should probably be "PDF/A-1a" format, which is not currently supported by Aeroo Reports and Aeroo DOCS. Support for this option can be developed, if you are interested in developing this feature, please contact me.

**Comment by sraps** [comment]
You can look at this "enhancement". I have not tested this by myself, so can not tell if it works or not, still  envision one drawback - the documents would take significantly more storage, because of embedded fonts, etc.
https://github.com/aeroo/aeroo_docs/issues/13

**Comment by mfzoutsource** [comment]
Thanks for your help @sraps, my aeroo report can display chinese and other characters too right now. For now my client just want it display in 'normal PDF', but it is good idea have PDF/A for aeroo report. But I'm not sure that I have time to look for that right now. And maybe one day :) 
Thanks again.
