### ISSUE TITLE
ProgrammingError: can't adapt type 'ir.actions.report.xml'

### ISSUE THREAD

**Issue by JosDeGraeve** [aeroo/aeroo_reports#74]
Hi,

This is imho not an aeroo issue, but i'm logging it here for other's reference.

When using a "print button", ie a button that triggers a method, returning an aeroo print action, triggers the error "can't adapt type 'ir.actions.report.xml'"

I have traced back the error to this PR: https://github.com/odoo/odoo/pull/9951

The root cause is that a recordset instead of an ids array is being passed as a parameter for ids with the old style api.  The PR fixes that.

The same issue is probably also present in v9

Regards,

**Comment by JosDeGraeve** [comment]
This is the fix for v9 community: https://github.com/odoo/odoo/pull/9962

**Comment by lukebranch** [comment]
@JosDeGraeve ,

Thanks for the fix. I found this one before I came across yours:

https://github.com/odoo/odoo/pull/10080/files

and the PR seems to have been accepted to the 8.0 branch for Odoo. I'm using the same change (in 10080) in Odoo 9.0 and it resolves the Aeroo reports issue.

Hopefully Odoo will merge the fix into 9.0 soon.
