### ISSUE TITLE
[8.0/9.0/Master] Parametric Link / Hyperlink for Images in Reports

### ISSUE THREAD

**Issue by lukebranch** [aeroo/aeroo_reports#87]
@sraps ,

Sorry to bother you, I know you're very busy. I'd just like to ask if you knew whether there was any way to add a hyperlink to an image in Aeroo Reports (eg. ODS reports with an image).

I have a need to add a product image into a report and then make that image clickable to link back to a product page or similar on my website, and i'm wondering if there was any way to do this with Aeroo Reports out of the box.

I had noticed this blueprint in Launchpad from awhile back:

https://blueprints.launchpad.net/aeroo/+spec/parametric-link
https://blueprints.dogfood.paddev.net/aeroo/+spec/parametric-link

which looks like it covers this use case, however i'm not sure if this feature was ever merged into Aeroo Reports or not.

If you have time please let me know if this feature exists in Aeroo, or would need to be developed.

**Comment by sraps** [comment]
It is possible since, I do not know, some three or more years. Unfortunately undocumented, due to lack of funds.

You have to insert image as you would ordinarily do by using frame object in ODT (sorry, have not tested with ODS by myself). Additionally fill in URL field in Hyperlink tab.
For example:
python://"http://www.alistek.com/"+gen_some_token(objects[0])

You will end up with clickable image.

**Comment by lukebranch** [comment]
@sraps ,

That's awesome news, thank you for your help.

Regarding funds, do you have any mechanism setup (eg. like a paypal account) for people to contribute to the project?

I personally don't think the crowdfunding method works very well for odoo, however having a way to be able to contribute to the Aeroo Reports project financially (ie. similar to how libreoffice allows people to contribute via paypal) may at least bring some funds together for the project.

I use Aeroo quite often for my own business, as i'm sure many others do, and I personally would be happy to contribute in this manner if there was a way to do so. I would not be able to afford much, however if enough people who are using the project contribute a small amount I'm guessing it could help fund some projects like expanding/updating the documentation.

Also, are you open to allowing community contributions to documentation, similar to what Odoo is doing here:

https://github.com/odoo/odoo/tree/9.0/doc

I'm sure some of the more experienced members using Aeroo Reports could contribute to some basic documentation, if you were interested in putting together a basic idea of what subjects you'd like it to cover.

**Comment by lukebranch** [comment]
FWIW, for anyone else needing this for ODS/Spreadsheets, it works in the same way as .doc, just open the hyperlink field in the template spreadsheet and add:

python://(replace with your object here)

for example I used the product manufacturer module here:

https://github.com/OCA/product-attribute/tree/9.0/product_manufacturer

and was just able to link to the URL field generated by this module by adding the following to the hyperlink part of the image in the ODS template as follows:

python://product.manufacturer_purl

once this is in the template this will provide a clickable image leading to that URL.
